name: diabetes-api
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - sqlalchemy
      - pymysql
      - "pydantic[email]"
      - pydantic-settings
      - python-dotenv
      - cryptography
