name: Super-Linter

on:
  push:
  pull_request:

permissions: {}

jobs:
  super-lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.3.0
        env: 
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONPATH: backend
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
